name = "GitSEO"
uuid = "f8e2c3a1-5b4d-4e6f-8a9b-0c1d2e3f4a5b"
authors = ["hyperpolymath"]
version = "0.1.0"

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
julia = "1.9"
Comonicon = "1"
HTTP = "1"
JSON3 = "1"
URIs = "1"
